query GetImage($id: ID!) {
  getImage(id: $id) {
    id
    previewID
    name
    description
    createdAt
    aspect
    author {
      name
    }
  }
}

query GetNewestImages($start: Int!, $count: Int!) {
  getNewestImages(start: $start, count: $count) {
    id
    previewID
    name
    description
    createdAt
    aspect
    author {
      name
    }
  }
}

query GetUserNewestImages($id: ID!, $start: Int!, $count: Int!) {
  getUserNewestImages(id: $id, start: $start, count: $count) {
    id
    previewID
    name
    description
    createdAt
    aspect
    author {
      name
    }
  }
}

mutation CreateImage($name: String!, $description: String!, $data: String!) {
  createImage(name: $name, description: $description, data: $data) {
    id
  }
}
